# Generated by Django 4.0.5 on 2022-09-24 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='lastseen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
