# Generated by Django 4.0.5 on 2022-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chatroom_msg_alter_chatroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
